http:
  port: "8090"
  
api:
  name: "cqrs-order-details-sys-api"
  
mysql:
  host: "localhost"
  port: "3307"
  user: "root"
  password : "password"
  database: "ecommerce"
  customertable: "customer"
  ordertable: "order_header"
  orderlinestable: "order_lines"

retry:
  threshold: "1"
  ttl: "5"
  