http:
  port: "8085"
  
api:
  name: "cqrs-order-sys-api"
  
mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password : "password"
  database: "ecommerce"
  ordertable: "order_header"

retry:
  threshold: "1"
  ttl: "5"
  